(function attachDataDisclosureTimeConfig(global) {
  global.BOSS_DATA_DISCLOSURE_TIME_CONFIG = {
  "sourceFile": "交易市场披露数据梳理-副本 (2).xlsx",
  "sourceSheets": [
    "广东交易中心-广东数据-取数工具",
    "陕西交易中心-陕西数据-取数工具",
    "湖南交易中心-湖南数据-取数工具"
  ],
  "tradeCenters": [
    {
      "key": "guangdong",
      "name": "广东交易中心"
    },
    {
      "key": "hunan",
      "name": "湖南交易中心"
    },
    {
      "key": "shaanxi",
      "name": "陕西交易中心"
    }
  ],
  "columns": [
    {
      "key": "tradeCenter",
      "label": "交易中心"
    },
    {
      "key": "dataCategory",
      "label": "数据分类"
    },
    {
      "key": "dataName",
      "label": "数据名称 / 数据分子"
    },
    {
      "key": "dataSubItem",
      "label": "数据子项"
    },
    {
      "key": "priority",
      "label": "优先级"
    },
    {
      "key": "timePoint",
      "label": "时间点位"
    },
    {
      "key": "pageAddress",
      "label": "页面地址"
    },
    {
      "key": "downloadFile",
      "label": "下载文件"
    },
    {
      "key": "disclosureTime",
      "label": "数据披露时间"
    },
    {
      "key": "valueRange",
      "label": "取值范围"
    },
    {
      "key": "fetchToolTimeliness",
      "label": "取数工具时效"
    },
    {
      "key": "remark",
      "label": "备注"
    }
  ],
  "rows": [
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "预测",
      "dataName": "负荷预测信息",
      "dataSubItem": "统调负荷(MW)",
      "priority": "P0",
      "timePoint": "15min",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "预测",
      "dataName": "负荷预测信息",
      "dataSubItem": "省内A类电源(MW)",
      "priority": "P0",
      "timePoint": "15min",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "预测",
      "dataName": "负荷预测信息",
      "dataSubItem": "省内B类电源(MW)",
      "priority": "P1",
      "timePoint": "15min",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "预测",
      "dataName": "负荷预测信息",
      "dataSubItem": "地方电源出力(MW)",
      "priority": "P0",
      "timePoint": "15min",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "预测",
      "dataName": "负荷预测信息",
      "dataSubItem": "粤港联络线(MW)",
      "priority": "P1",
      "timePoint": "15min",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "实际",
      "dataName": "负荷实际信息",
      "dataSubItem": "统调负荷(MW)",
      "priority": "P0",
      "timePoint": "15min",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "实际",
      "dataName": "负荷实际信息",
      "dataSubItem": "省内A类电源(MW)",
      "priority": "P0",
      "timePoint": "15min",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "实际",
      "dataName": "负荷实际信息",
      "dataSubItem": "省内B类电源(MW)",
      "priority": "P1",
      "timePoint": "15min",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "实际",
      "dataName": "负荷实际信息",
      "dataSubItem": "地方电源出力(MW)",
      "priority": "P0",
      "timePoint": "15min",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "实际",
      "dataName": "负荷实际信息",
      "dataSubItem": "西电东送电力(MW)",
      "priority": "P0",
      "timePoint": "15min",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "实际",
      "dataName": "负荷实际信息",
      "dataSubItem": "粤港联络线(MW)",
      "priority": "P1",
      "timePoint": "15min",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "预测",
      "dataName": "地方电预测信息",
      "dataSubItem": "风电(MW)",
      "priority": "P1",
      "timePoint": "15min",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "预测",
      "dataName": "地方电预测信息",
      "dataSubItem": "光伏(MW)",
      "priority": "P1",
      "timePoint": "15min",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "预测",
      "dataName": "地方电预测信息",
      "dataSubItem": "火电(MW)",
      "priority": "P1",
      "timePoint": "15min",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "预测",
      "dataName": "地方电预测信息",
      "dataSubItem": "水电(MW)",
      "priority": "P1",
      "timePoint": "15min",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "实际",
      "dataName": "地方电实际信息",
      "dataSubItem": "风电(MW)",
      "priority": "P1",
      "timePoint": "15min",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "实际",
      "dataName": "地方电实际信息",
      "dataSubItem": "光伏(MW)",
      "priority": "P1",
      "timePoint": "15min",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "实际",
      "dataName": "地方电实际信息",
      "dataSubItem": "火电(MW)",
      "priority": "P1",
      "timePoint": "15min",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "实际",
      "dataName": "地方电实际信息",
      "dataSubItem": "水电(MW)",
      "priority": "P1",
      "timePoint": "15min",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "实际",
      "dataName": "地方电实际信息",
      "dataSubItem": "生物质(MW)",
      "priority": "P1",
      "timePoint": "15min",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "实际",
      "dataName": "地方电实际信息",
      "dataSubItem": "其他(MW)",
      "priority": "P1",
      "timePoint": "15min",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "实际",
      "dataName": "西电东送各通道实际信息",
      "dataSubItem": "三峡(MW)",
      "priority": "P0",
      "timePoint": "15min",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "实际",
      "dataName": "西电东送各通道实际信息",
      "dataSubItem": "兴安直流(MW)",
      "priority": "P0",
      "timePoint": "15min",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "实际",
      "dataName": "西电东送各通道实际信息",
      "dataSubItem": "天广直流(MW)",
      "priority": "P0",
      "timePoint": "15min",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "实际",
      "dataName": "西电东送各通道实际信息",
      "dataSubItem": "新东直流(MW)",
      "priority": "P0",
      "timePoint": "15min",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "实际",
      "dataName": "西电东送各通道实际信息",
      "dataSubItem": "昆柳龙直流(MW)",
      "priority": "P0",
      "timePoint": "15min",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "实际",
      "dataName": "西电东送各通道实际信息",
      "dataSubItem": "普侨直流(MW)",
      "priority": "P0",
      "timePoint": "15min",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "实际",
      "dataName": "西电东送各通道实际信息",
      "dataSubItem": "楚穗直流(MW)",
      "priority": "P0",
      "timePoint": "15min",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "实际",
      "dataName": "西电东送各通道实际信息",
      "dataSubItem": "海南送广东总加(MW)",
      "priority": "P0",
      "timePoint": "15min",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "实际",
      "dataName": "西电东送各通道实际信息",
      "dataSubItem": "牛从直流(MW)",
      "priority": "P0",
      "timePoint": "15min",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "实际",
      "dataName": "西电东送各通道实际信息",
      "dataSubItem": "玉茂桂山贺罗梧罗总加(MW)",
      "priority": "P0",
      "timePoint": "15min",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "实际",
      "dataName": "西电东送各通道实际信息",
      "dataSubItem": "高肇直流(MW)",
      "priority": "P0",
      "timePoint": "15min",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "预测",
      "dataName": "机组检修容量预测信息",
      "dataSubItem": "--",
      "priority": "P0",
      "timePoint": "1D",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "实际",
      "dataName": "机组检修容量实际信息",
      "dataSubItem": "--",
      "priority": "--",
      "timePoint": "1D",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "预测",
      "dataName": "备用预测信息",
      "dataSubItem": "正备用(MW)",
      "priority": "P0",
      "timePoint": "15min",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "预测",
      "dataName": "备用预测信息",
      "dataSubItem": "负备用(MW)",
      "priority": "P0",
      "timePoint": "15min",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "预测",
      "dataName": "备用预测信息",
      "dataSubItem": "一次调频备用(MW)",
      "priority": "P1",
      "timePoint": "15min",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "实际",
      "dataName": "备用实际信息",
      "dataSubItem": "正备用(MW)",
      "priority": "--",
      "timePoint": "15min",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "实际",
      "dataName": "备用实际信息",
      "dataSubItem": "负备用(MW)",
      "priority": "--",
      "timePoint": "15min",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "实际",
      "dataName": "备用实际信息",
      "dataSubItem": "一次调频备用(MW)",
      "priority": "--",
      "timePoint": "15min",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "预测",
      "dataName": "统调新能源出力信息",
      "dataSubItem": "光伏出力预测(MW)",
      "priority": "P0",
      "timePoint": "15min",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "预测",
      "dataName": "统调新能源出力信息",
      "dataSubItem": "风电出力预测(MW)",
      "priority": "P0",
      "timePoint": "15min",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "实际",
      "dataName": "实时出清断面",
      "dataSubItem": "--",
      "priority": "--",
      "timePoint": "15min",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "实际",
      "dataName": "实际断面",
      "dataSubItem": "--",
      "priority": "--",
      "timePoint": "15min",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "预测",
      "dataName": "必开必停容量预测信息",
      "dataSubItem": "--",
      "priority": "--",
      "timePoint": "1D",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "实际",
      "dataName": "必开必停容量实际信息",
      "dataSubItem": "--",
      "priority": "--",
      "timePoint": "1D",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "实际",
      "dataName": "输变电设备检修计划执行情况",
      "dataSubItem": "--",
      "priority": "--",
      "timePoint": "日期范围",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "预测",
      "dataName": "发电总出力预测信息",
      "dataSubItem": "--",
      "priority": "--",
      "timePoint": "15min",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "实际",
      "dataName": "机组出力情况",
      "dataSubItem": "发电总出力(MW)",
      "priority": "--",
      "timePoint": "15min",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "预测",
      "dataName": "水电（含抽蓄）总出力预测信息",
      "dataSubItem": "--",
      "priority": "--",
      "timePoint": "15min",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "实际",
      "dataName": "机组出力情况",
      "dataSubItem": "水电（含抽蓄）总出力(MW)",
      "priority": "--",
      "timePoint": "15min",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "实际",
      "dataName": "机组出力情况",
      "dataSubItem": "统调系统实际负荷(MW)",
      "priority": "--",
      "timePoint": "15min",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "实际",
      "dataName": "机组出力情况",
      "dataSubItem": "新能源总出力(MW)",
      "priority": "--",
      "timePoint": "15min",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "预测",
      "dataName": "现货新能源总出力",
      "dataSubItem": "D日",
      "priority": "--",
      "timePoint": "15min",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "预测",
      "dataName": "现货新能源总出力",
      "dataSubItem": "D+1日",
      "priority": "--",
      "timePoint": "15min",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "预测",
      "dataName": "现货新能源总出力",
      "dataSubItem": "D+2日",
      "priority": "--",
      "timePoint": "15min",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "预测",
      "dataName": "抽蓄电站出力计划",
      "dataSubItem": "--",
      "priority": "--",
      "timePoint": "15min",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "预测",
      "dataName": "机组检修预测信息",
      "dataSubItem": "--",
      "priority": "--",
      "timePoint": "日期范围",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "预测",
      "dataName": "输变电检修预测信息",
      "dataSubItem": "--",
      "priority": "--",
      "timePoint": "1D",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "实际",
      "dataName": "售电公司分时电量",
      "dataSubItem": "--",
      "priority": "--",
      "timePoint": "1H",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "实际",
      "dataName": "用电企业分时电量",
      "dataSubItem": "--",
      "priority": "--",
      "timePoint": "1H",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "日前",
      "dataName": "日前开机台数和出清电量",
      "dataSubItem": "电量",
      "priority": "P0",
      "timePoint": "1H",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "日前",
      "dataName": "日前开机台数和出清电量",
      "dataSubItem": "开机台数",
      "priority": "P0",
      "timePoint": "1H",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "实时",
      "dataName": "实时开机台数和出清电量",
      "dataSubItem": "电量",
      "priority": "P0",
      "timePoint": "1H",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "实时",
      "dataName": "实时开机台数和出清电量",
      "dataSubItem": "开机台数",
      "priority": "P0",
      "timePoint": "1H",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "日前",
      "dataName": "日前交易结果",
      "dataSubItem": "日前统一结算价",
      "priority": "--",
      "timePoint": "1H",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "日前",
      "dataName": "日前交易结果",
      "dataSubItem": "日前成交电量",
      "priority": "--",
      "timePoint": "1H",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "实时",
      "dataName": "实时交易结果",
      "dataSubItem": "实时统一结算价",
      "priority": "--",
      "timePoint": "1H",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "实时",
      "dataName": "实时交易结果",
      "dataSubItem": "实际用电量",
      "priority": "--",
      "timePoint": "1H",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "日前",
      "dataName": "日前节点电价",
      "dataSubItem": "--",
      "priority": "--",
      "timePoint": "15min",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "实时",
      "dataName": "实时节点电价",
      "dataSubItem": "--",
      "priority": "--",
      "timePoint": "15min",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "实际",
      "dataName": "日前申报",
      "dataSubItem": "--",
      "priority": "--",
      "timePoint": "1H",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "实际",
      "dataName": "日清算结果",
      "dataSubItem": "--",
      "priority": "--",
      "timePoint": "总/1H",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "实际",
      "dataName": "月结算结果",
      "dataSubItem": "--",
      "priority": "--",
      "timePoint": "1M",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "实际",
      "dataName": "月结算明细",
      "dataSubItem": "--",
      "priority": "--",
      "timePoint": "1M",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "guangdong",
      "tradeCenter": "广东交易中心",
      "sourceSheet": "广东交易中心-广东数据-取数工具",
      "dataCategory": "实际",
      "dataName": "零售关系",
      "dataSubItem": "--",
      "priority": "--",
      "timePoint": "1Y",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "shaanxi",
      "tradeCenter": "陕西交易中心",
      "sourceSheet": "陕西交易中心-陕西数据-取数工具",
      "dataCategory": "预测",
      "dataName": "系统负荷预测（日）",
      "dataSubItem": "--",
      "priority": "P0",
      "timePoint": "15min",
      "pageAddress": "信息披露-省内现货-系统负荷预测（日）",
      "downloadFile": "2026-05-08snLoadSupplyAndDemandBalance.xlsx",
      "disclosureTime": "D日出D+1日",
      "valueRange": "D-3至D+1",
      "fetchToolTimeliness": "6点、8点、12点、14点、23点各取一次",
      "remark": "--"
    },
    {
      "tradeCenterKey": "shaanxi",
      "tradeCenter": "陕西交易中心",
      "sourceSheet": "陕西交易中心-陕西数据-取数工具",
      "dataCategory": "实际",
      "dataName": "实际负荷",
      "dataSubItem": "--",
      "priority": "P0",
      "timePoint": "15min",
      "pageAddress": "信息披露-省内现货-实际负荷",
      "downloadFile": "2026-05-08snDwsjfhplby.xlsx",
      "disclosureTime": "D日12时后出D-1日",
      "valueRange": "D-4至D-1",
      "fetchToolTimeliness": "6点、8点、12点、14点、23点各取一次",
      "remark": "--"
    },
    {
      "tradeCenterKey": "shaanxi",
      "tradeCenter": "陕西交易中心",
      "sourceSheet": "陕西交易中心-陕西数据-取数工具",
      "dataCategory": "预测",
      "dataName": "发电总出力预测",
      "dataSubItem": "--",
      "priority": "P0",
      "timePoint": "15min",
      "pageAddress": "信息披露-省内现货-发电总出力预测",
      "downloadFile": "2026-05-08snRqgjysdfdzcljfqclyc.xlsx",
      "disclosureTime": "D日出D+1日",
      "valueRange": "D-3至D+1",
      "fetchToolTimeliness": "6点、8点、12点、14点、23点各取一次",
      "remark": "--"
    },
    {
      "tradeCenterKey": "shaanxi",
      "tradeCenter": "陕西交易中心",
      "sourceSheet": "陕西交易中心-陕西数据-取数工具",
      "dataCategory": "实际",
      "dataName": "发电总出力",
      "dataSubItem": "--",
      "priority": "P0",
      "timePoint": "15min",
      "pageAddress": "信息披露-省内现货-发电总出力",
      "downloadFile": "--",
      "disclosureTime": "D日12时后出D-1日",
      "valueRange": "D-7->D-1",
      "fetchToolTimeliness": "--",
      "remark": "无文件导出"
    },
    {
      "tradeCenterKey": "shaanxi",
      "tradeCenter": "陕西交易中心",
      "sourceSheet": "陕西交易中心-陕西数据-取数工具",
      "dataCategory": "预测",
      "dataName": "非市场机组总出力预测",
      "dataSubItem": "--",
      "priority": "P0",
      "timePoint": "15min",
      "pageAddress": "信息披露-省内现货-非市场机组总出力预测",
      "downloadFile": "2026-05-08snRqglfscjzclyc.xlsx",
      "disclosureTime": "D日出D+1日",
      "valueRange": "D-3至D+1",
      "fetchToolTimeliness": "6点、8点、12点、14点、23点各取一次",
      "remark": "--"
    },
    {
      "tradeCenterKey": "shaanxi",
      "tradeCenter": "陕西交易中心",
      "sourceSheet": "陕西交易中心-陕西数据-取数工具",
      "dataCategory": "实际",
      "dataName": "非市场机组总出力",
      "dataSubItem": "--",
      "priority": "P0",
      "timePoint": "15min",
      "pageAddress": "信息披露-省内现货-非市场机组总出力",
      "downloadFile": "--",
      "disclosureTime": "D日12时后出D-1日",
      "valueRange": "D-4至D-1",
      "fetchToolTimeliness": "6点、8点、12点、14点、23点各取一次",
      "remark": "无文件导出"
    },
    {
      "tradeCenterKey": "shaanxi",
      "tradeCenter": "陕西交易中心",
      "sourceSheet": "陕西交易中心-陕西数据-取数工具",
      "dataCategory": "预测",
      "dataName": "新能源总出力预测（日）",
      "dataSubItem": "新能源总出力预测数值",
      "priority": "P0",
      "timePoint": "15min",
      "pageAddress": "信息披露-省内现货-新能源总出力预测（日）",
      "downloadFile": "2026-05-08snRqxnyzcljflclyc.xlsx",
      "disclosureTime": "D日出D+1日",
      "valueRange": "D-3至D+1",
      "fetchToolTimeliness": "6点、8点、12点、14点、23点各取一次",
      "remark": "--"
    },
    {
      "tradeCenterKey": "shaanxi",
      "tradeCenter": "陕西交易中心",
      "sourceSheet": "陕西交易中心-陕西数据-取数工具",
      "dataCategory": "预测",
      "dataName": "新能源总出力预测（日）",
      "dataSubItem": "光电总出力预测数值",
      "priority": "P0",
      "timePoint": "15min",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "shaanxi",
      "tradeCenter": "陕西交易中心",
      "sourceSheet": "陕西交易中心-陕西数据-取数工具",
      "dataCategory": "预测",
      "dataName": "新能源总出力预测（日）",
      "dataSubItem": "风电总出力预测数值",
      "priority": "P0",
      "timePoint": "15min",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "shaanxi",
      "tradeCenter": "陕西交易中心",
      "sourceSheet": "陕西交易中心-陕西数据-取数工具",
      "dataCategory": "实际",
      "dataName": "新能源总出力",
      "dataSubItem": "新能源总出力",
      "priority": "P0",
      "timePoint": "15min",
      "pageAddress": "信息披露-省内现货-新能源总出力",
      "downloadFile": "2026-05-08snXnyzcljflxcl.xlsx",
      "disclosureTime": "D日12时后出D-1日",
      "valueRange": "D-4至D-1",
      "fetchToolTimeliness": "6点、8点、12点、14点、23点各取一次",
      "remark": "--"
    },
    {
      "tradeCenterKey": "shaanxi",
      "tradeCenter": "陕西交易中心",
      "sourceSheet": "陕西交易中心-陕西数据-取数工具",
      "dataCategory": "实际",
      "dataName": "新能源总出力",
      "dataSubItem": "光伏总出力",
      "priority": "P0",
      "timePoint": "15min",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "shaanxi",
      "tradeCenter": "陕西交易中心",
      "sourceSheet": "陕西交易中心-陕西数据-取数工具",
      "dataCategory": "实际",
      "dataName": "新能源总出力",
      "dataSubItem": "风电总出力",
      "priority": "P0",
      "timePoint": "15min",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "shaanxi",
      "tradeCenter": "陕西交易中心",
      "sourceSheet": "陕西交易中心-陕西数据-取数工具",
      "dataCategory": "预测",
      "dataName": "水电（含抽蓄）总出力预测（日）",
      "dataSubItem": "--",
      "priority": "P0",
      "timePoint": "15min",
      "pageAddress": "信息披露-省内现货-水电（含抽蓄）出力",
      "downloadFile": "2026-05-08snRqsdfdclyc.xlsx",
      "disclosureTime": "D日出D+1日",
      "valueRange": "D-3至D+1",
      "fetchToolTimeliness": "6点、8点、12点、14点、23点各取一次",
      "remark": "--"
    },
    {
      "tradeCenterKey": "shaanxi",
      "tradeCenter": "陕西交易中心",
      "sourceSheet": "陕西交易中心-陕西数据-取数工具",
      "dataCategory": "实际",
      "dataName": "水电（含抽蓄）出力",
      "dataSubItem": "--",
      "priority": "P0",
      "timePoint": "15min",
      "pageAddress": "信息披露-省内现货-水电（含抽蓄）出力",
      "downloadFile": "--",
      "disclosureTime": "D日12时后出D-1日",
      "valueRange": "D-4至D-1",
      "fetchToolTimeliness": "6点、8点、12点、14点、23点各取一次",
      "remark": "无文件导出"
    },
    {
      "tradeCenterKey": "shaanxi",
      "tradeCenter": "陕西交易中心",
      "sourceSheet": "陕西交易中心-陕西数据-取数工具",
      "dataCategory": "预测",
      "dataName": "省间联络线输电曲线预测",
      "dataSubItem": "外来电交易计划",
      "priority": "P0",
      "timePoint": "15min",
      "pageAddress": "信息披露-省内现货-省间联络线输电曲线预测",
      "downloadFile": "2026-05-08snTieLineCurrent.xlsx",
      "disclosureTime": "日前：D日出D+1日\n日内：D日出D日",
      "valueRange": "D-3至D+1",
      "fetchToolTimeliness": "6点、8点、12点、14点、23点各取一次",
      "remark": "--"
    },
    {
      "tradeCenterKey": "shaanxi",
      "tradeCenter": "陕西交易中心",
      "sourceSheet": "陕西交易中心-陕西数据-取数工具",
      "dataCategory": "实际",
      "dataName": "省间联络线输电情况",
      "dataSubItem": "--",
      "priority": "P0",
      "timePoint": "15min",
      "pageAddress": "信息披露-省内现货- 省间联络线输电情况",
      "downloadFile": "--",
      "disclosureTime": "D日12时后出D-1日",
      "valueRange": "D-4至D-1",
      "fetchToolTimeliness": "6点、8点、12点、14点、23点各取一次",
      "remark": "无文件导出"
    },
    {
      "tradeCenterKey": "shaanxi",
      "tradeCenter": "陕西交易中心",
      "sourceSheet": "陕西交易中心-陕西数据-取数工具",
      "dataCategory": "日前",
      "dataName": "用户侧加权电价",
      "dataSubItem": "--",
      "priority": "P0",
      "timePoint": "15min",
      "pageAddress": "现货交易-用户侧加权电价",
      "downloadFile": "--",
      "disclosureTime": "日前：D日22点出D+1日",
      "valueRange": "日前：D-3->D+1",
      "fetchToolTimeliness": "6点、8点、12点、14点、23点各取一次",
      "remark": "无文件导出"
    },
    {
      "tradeCenterKey": "shaanxi",
      "tradeCenter": "陕西交易中心",
      "sourceSheet": "陕西交易中心-陕西数据-取数工具",
      "dataCategory": "实时",
      "dataName": "用户侧加权电价",
      "dataSubItem": "--",
      "priority": "P0",
      "timePoint": "15min",
      "pageAddress": "现货交易-用户侧加权电价",
      "downloadFile": "--",
      "disclosureTime": "实时：D日出D-1日",
      "valueRange": "实时 D-3>D-1",
      "fetchToolTimeliness": "6点、8点、12点、14点、23点各取一次",
      "remark": "--"
    },
    {
      "tradeCenterKey": "shaanxi",
      "tradeCenter": "陕西交易中心",
      "sourceSheet": "陕西交易中心-陕西数据-取数工具",
      "dataCategory": "实际",
      "dataName": "售电公司日电量",
      "dataSubItem": "--",
      "priority": "P0",
      "timePoint": "15min",
      "pageAddress": "信息披露-售电公司日电量",
      "downloadFile": "2026-05-01用户侧实际用电量.xlsx",
      "disclosureTime": "D日出D-2日",
      "valueRange": "D-1->D-2",
      "fetchToolTimeliness": "6点、8点、12点、14点、23点各取一次",
      "remark": "--"
    },
    {
      "tradeCenterKey": "shaanxi",
      "tradeCenter": "陕西交易中心",
      "sourceSheet": "陕西交易中心-陕西数据-取数工具",
      "dataCategory": "实际",
      "dataName": "日滚搓量价（卖1至卖5，买1至买5）",
      "dataSubItem": "--",
      "priority": "P0",
      "timePoint": "10s",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "shaanxi",
      "tradeCenter": "陕西交易中心",
      "sourceSheet": "陕西交易中心-陕西数据-取数工具",
      "dataCategory": "实际",
      "dataName": "日前申报",
      "dataSubItem": "--",
      "priority": "--",
      "timePoint": "15min",
      "pageAddress": "现货交易-现货申报_用电侧",
      "downloadFile": "电能量申报数据.xlsx",
      "disclosureTime": "D日申报后即有数据",
      "valueRange": "D至D+1",
      "fetchToolTimeliness": "14点取一次",
      "remark": "--"
    },
    {
      "tradeCenterKey": "shaanxi",
      "tradeCenter": "陕西交易中心",
      "sourceSheet": "陕西交易中心-陕西数据-取数工具",
      "dataCategory": "实际",
      "dataName": "中长期合同曲线",
      "dataSubItem": "--",
      "priority": "P0",
      "timePoint": "15min",
      "pageAddress": "我的合同-中长期合同曲线-中长期合同曲线明细",
      "downloadFile": "2026-05-08,2026-05-08中长期合同曲线明细.xlsx",
      "disclosureTime": "--",
      "valueRange": "D至D+10",
      "fetchToolTimeliness": "14点取一次",
      "remark": "--"
    },
    {
      "tradeCenterKey": "shaanxi",
      "tradeCenter": "陕西交易中心",
      "sourceSheet": "陕西交易中心-陕西数据-取数工具",
      "dataCategory": "实际",
      "dataName": "机组状态",
      "dataSubItem": "--",
      "priority": "P2",
      "timePoint": "15min",
      "pageAddress": "信息披露-综合查询-电网运行-机组状态",
      "downloadFile": "--",
      "disclosureTime": "D日实时滚动更新",
      "valueRange": "D-1至D日",
      "fetchToolTimeliness": "6点、8点、12点、14点、23点各取一次",
      "remark": "--"
    },
    {
      "tradeCenterKey": "shaanxi",
      "tradeCenter": "陕西交易中心",
      "sourceSheet": "陕西交易中心-陕西数据-取数工具",
      "dataCategory": "实际",
      "dataName": "交易总体情况（交易）",
      "dataSubItem": "--",
      "priority": "P1",
      "timePoint": "1H",
      "pageAddress": "信息披露-综合查询-市场运营-交易组织及出清-交易总体情况（交易）",
      "downloadFile": "2026年05月08日售电公司中长期批发侧价格参数信息披露.pdf",
      "disclosureTime": "不定时",
      "valueRange": "D-7至D+1日",
      "fetchToolTimeliness": "14点取一次",
      "remark": "--"
    },
    {
      "tradeCenterKey": "shaanxi",
      "tradeCenter": "陕西交易中心",
      "sourceSheet": "陕西交易中心-陕西数据-取数工具",
      "dataCategory": "实际",
      "dataName": "日清算",
      "dataSubItem": "--",
      "priority": "P2",
      "timePoint": "15min",
      "pageAddress": "我的结算-用户侧日清分账单",
      "downloadFile": "2026-04-30用户侧日清分账单.xlsx",
      "disclosureTime": "D日出D-2日",
      "valueRange": "D-5至D-2日",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "shaanxi",
      "tradeCenter": "陕西交易中心",
      "sourceSheet": "陕西交易中心-陕西数据-取数工具",
      "dataCategory": "实际",
      "dataName": "月结算-售电公司",
      "dataSubItem": "--",
      "priority": "P0",
      "timePoint": "1M",
      "pageAddress": "我的结算-结算单确认（新）-用电侧-售电公司交易结算单",
      "downloadFile": "北京小桔新能源汽车科技有限公司2026-03-01.pdf",
      "disclosureTime": "M月9日后出M-1月数据",
      "valueRange": "M-1月",
      "fetchToolTimeliness": "M月9日取到一次即可",
      "remark": "--"
    },
    {
      "tradeCenterKey": "shaanxi",
      "tradeCenter": "陕西交易中心",
      "sourceSheet": "陕西交易中心-陕西数据-取数工具",
      "dataCategory": "实际",
      "dataName": "月结算-用电企业",
      "dataSubItem": "--",
      "priority": "P0",
      "timePoint": "1M",
      "pageAddress": "我的结算-结算单确认（新）-用电侧-售电公司交易结算明细（售电侧）",
      "downloadFile": "北京小桔新能源汽车科技有限公司2026-03-01.xlsx",
      "disclosureTime": "M月9日后出M-1月数据",
      "valueRange": "M-1月",
      "fetchToolTimeliness": "M月9日取到一次即可",
      "remark": "--"
    },
    {
      "tradeCenterKey": "shaanxi",
      "tradeCenter": "陕西交易中心",
      "sourceSheet": "陕西交易中心-陕西数据-取数工具",
      "dataCategory": "实际",
      "dataName": "系统备用信息",
      "dataSubItem": "--",
      "priority": "P0",
      "timePoint": "15min",
      "pageAddress": "信息披露-省内现货-系统备用信息",
      "downloadFile": "--",
      "disclosureTime": "D日出D-1日",
      "valueRange": "D-7->D+1",
      "fetchToolTimeliness": "--",
      "remark": "无文件导出"
    },
    {
      "tradeCenterKey": "shaanxi",
      "tradeCenter": "陕西交易中心",
      "sourceSheet": "陕西交易中心-陕西数据-取数工具",
      "dataCategory": "日前",
      "dataName": "日前现货市场节点边际电价（日）",
      "dataSubItem": "--",
      "priority": "--",
      "timePoint": "--",
      "pageAddress": "信息披露-市场运营-交易组织及出清-日前现货市场节点边际电价（日）",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "shaanxi",
      "tradeCenter": "陕西交易中心",
      "sourceSheet": "陕西交易中心-陕西数据-取数工具",
      "dataCategory": "实时",
      "dataName": "实时现货市场节点边际电价（日）",
      "dataSubItem": "--",
      "priority": "--",
      "timePoint": "--",
      "pageAddress": "信息披露-市场运营-交易组织及出清-实时现货市场节点边际电价（日）",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "hunan",
      "tradeCenter": "湖南交易中心",
      "sourceSheet": "湖南交易中心-湖南数据-取数工具",
      "dataCategory": "预测",
      "dataName": "系统负荷预测（日）",
      "dataSubItem": "--",
      "priority": "P0",
      "timePoint": "15min",
      "pageAddress": "信息披露-信息披露查询-现货及辅助服务-省内现货-预测信息-系统负荷预测（日）",
      "downloadFile": "5.1.______【事前日】系统负荷预测-日.xlsx",
      "disclosureTime": "D日出D+1日",
      "valueRange": "D-3至D+1",
      "fetchToolTimeliness": "6点、8点、12点、14点、23点各取一次",
      "remark": "--"
    },
    {
      "tradeCenterKey": "hunan",
      "tradeCenter": "湖南交易中心",
      "sourceSheet": "湖南交易中心-湖南数据-取数工具",
      "dataCategory": "实际",
      "dataName": "实际负荷",
      "dataSubItem": "--",
      "priority": "P0",
      "timePoint": "15min",
      "pageAddress": "信息披露-信息披露查询-现货及辅助服务-省内现货-运行信息-实际负荷",
      "downloadFile": "8.6._【事后】实际负荷.xlsx",
      "disclosureTime": "D日12时后出D-1日",
      "valueRange": "D-4至D-1",
      "fetchToolTimeliness": "6点、8点、12点、14点、23点各取一次",
      "remark": "--"
    },
    {
      "tradeCenterKey": "hunan",
      "tradeCenter": "湖南交易中心",
      "sourceSheet": "湖南交易中心-湖南数据-取数工具",
      "dataCategory": "预测",
      "dataName": "新能源总出力预测（日）",
      "dataSubItem": "--",
      "priority": "P0",
      "timePoint": "15min",
      "pageAddress": "信息披露-信息披露查询-现货及辅助服务-省内现货-预测信息-新能源总出力预测（日）",
      "downloadFile": "5.7._【事前】新能源总出力预测.xlsx",
      "disclosureTime": "D日出D+1日",
      "valueRange": "D-3至D+1",
      "fetchToolTimeliness": "6点、8点、12点、14点、23点各取一次",
      "remark": "--"
    },
    {
      "tradeCenterKey": "hunan",
      "tradeCenter": "湖南交易中心",
      "sourceSheet": "湖南交易中心-湖南数据-取数工具",
      "dataCategory": "实际",
      "dataName": "新能源总出力",
      "dataSubItem": "湖南风电发电有功电力",
      "priority": "P0",
      "timePoint": "15min",
      "pageAddress": "信息披露-信息披露查询-现货及辅助服务-省内现货-运行信息-新能源总出力",
      "downloadFile": "8.4._【事后】新能源总出力 (2).xlsx",
      "disclosureTime": "D日12时后出D-1日",
      "valueRange": "D-4至D-1",
      "fetchToolTimeliness": "6点、8点、12点、14点、23点各取一次",
      "remark": "--"
    },
    {
      "tradeCenterKey": "hunan",
      "tradeCenter": "湖南交易中心",
      "sourceSheet": "湖南交易中心-湖南数据-取数工具",
      "dataCategory": "实际",
      "dataName": "新能源总出力",
      "dataSubItem": "湖南光伏发电有功电力",
      "priority": "--",
      "timePoint": "15min",
      "pageAddress": "信息披露-信息披露查询-现货及辅助服务-省内现货-运行信息-新能源总出力",
      "downloadFile": "--",
      "disclosureTime": "D日12时后出D-1日",
      "valueRange": "D-4至D-1",
      "fetchToolTimeliness": "6点、8点、12点、14点、23点各取一次",
      "remark": "--"
    },
    {
      "tradeCenterKey": "hunan",
      "tradeCenter": "湖南交易中心",
      "sourceSheet": "湖南交易中心-湖南数据-取数工具",
      "dataCategory": "预测",
      "dataName": "水电（含抽蓄）总出力预测(日）",
      "dataSubItem": "水电总出力预测",
      "priority": "P0",
      "timePoint": "15min",
      "pageAddress": "信息披露-信息披露查询-现货及辅助服务-省内现货-预测信息-水电（含抽蓄）总出力预测（日）",
      "downloadFile": "5.9._【事前】水电（含抽蓄）总出力预测-日 (5).xlsx",
      "disclosureTime": "D日出D+1日",
      "valueRange": "D-3至D+1",
      "fetchToolTimeliness": "6点、8点、12点、14点、23点各取一次",
      "remark": "--"
    },
    {
      "tradeCenterKey": "hunan",
      "tradeCenter": "湖南交易中心",
      "sourceSheet": "湖南交易中心-湖南数据-取数工具",
      "dataCategory": "实际",
      "dataName": "水电（含抽蓄）总出力",
      "dataSubItem": "湖南水电发电有功电力",
      "priority": "P0",
      "timePoint": "15min",
      "pageAddress": "信息披露-信息披露查询-现货及辅助服务-省内现货-运行信息-水电（含抽蓄）总出力",
      "downloadFile": "8.5._【事后】水电（含抽蓄）总出力 (1).xlsx",
      "disclosureTime": "D日12时后出D-1日",
      "valueRange": "D-4至D-1",
      "fetchToolTimeliness": "6点、8点、12点、14点、23点各取一次",
      "remark": "--"
    },
    {
      "tradeCenterKey": "hunan",
      "tradeCenter": "湖南交易中心",
      "sourceSheet": "湖南交易中心-湖南数据-取数工具",
      "dataCategory": "预测",
      "dataName": "省间联络线输电曲线预测",
      "dataSubItem": "中衡直流（日前）",
      "priority": "P0",
      "timePoint": "15min",
      "pageAddress": "信息披露-信息披露查询-现货及辅助服务-省内现货-预测信息-省间联络线输电曲线预测",
      "downloadFile": "5.4._【事前】省间联络线输电曲线预测.xlsx",
      "disclosureTime": "日前：D日出D+1日\n日内：D日出D日",
      "valueRange": "D-3至D+1",
      "fetchToolTimeliness": "6点、8点、12点、14点、23点各取一次",
      "remark": "--"
    },
    {
      "tradeCenterKey": "hunan",
      "tradeCenter": "湖南交易中心",
      "sourceSheet": "湖南交易中心-湖南数据-取数工具",
      "dataCategory": "预测",
      "dataName": "省间联络线输电曲线预测",
      "dataSubItem": "主网送湘（日前）",
      "priority": "P0",
      "timePoint": "15min",
      "pageAddress": "信息披露-信息披露查询-现货及辅助服务-省内现货-预测信息-省间联络线输电曲线预测",
      "downloadFile": "--",
      "disclosureTime": "日前：D日出D+1日\n日内：D日出D日",
      "valueRange": "D-3至D+1",
      "fetchToolTimeliness": "6点、8点、12点、14点、23点各取一次",
      "remark": "--"
    },
    {
      "tradeCenterKey": "hunan",
      "tradeCenter": "湖南交易中心",
      "sourceSheet": "湖南交易中心-湖南数据-取数工具",
      "dataCategory": "预测",
      "dataName": "省间联络线输电曲线预测",
      "dataSubItem": "祁韶直流（日前）",
      "priority": "P0",
      "timePoint": "15min",
      "pageAddress": "信息披露-信息披露查询-现货及辅助服务-省内现货-预测信息-省间联络线输电曲线预测",
      "downloadFile": "--",
      "disclosureTime": "日前：D日出D+1日\n日内：D日出D日",
      "valueRange": "D-3至D+1",
      "fetchToolTimeliness": "6点、8点、12点、14点、23点各取一次",
      "remark": "--"
    },
    {
      "tradeCenterKey": "hunan",
      "tradeCenter": "湖南交易中心",
      "sourceSheet": "湖南交易中心-湖南数据-取数工具",
      "dataCategory": "实际",
      "dataName": "省间联络线输电情况",
      "dataSubItem": "省间联络线实际输电情况",
      "priority": "P0",
      "timePoint": "15min",
      "pageAddress": "信息披露-信息披露查询-现货及辅助服务-省内现货-运行信息-省间联络线输电情况",
      "downloadFile": "8.10._【事后】省间联络线输电情况.xlsx",
      "disclosureTime": "D日12时后出D-1日",
      "valueRange": "D-4至D-1",
      "fetchToolTimeliness": "6点、8点、12点、14点、23点各取一次",
      "remark": "--"
    },
    {
      "tradeCenterKey": "hunan",
      "tradeCenter": "湖南交易中心",
      "sourceSheet": "湖南交易中心-湖南数据-取数工具",
      "dataCategory": "预测",
      "dataName": "发电总出力预测",
      "dataSubItem": "机组发电总出力预测",
      "priority": "P0",
      "timePoint": "15min",
      "pageAddress": "信息披露-信息披露查询-现货及辅助服务-省内现货-预测信息-发电总出力预测",
      "downloadFile": "5.5._【事前】发电总出力预测.xlsx",
      "disclosureTime": "D日出D+1日",
      "valueRange": "D-3至D+1",
      "fetchToolTimeliness": "6点、8点、12点、14点、23点各取一次",
      "remark": "--"
    },
    {
      "tradeCenterKey": "hunan",
      "tradeCenter": "湖南交易中心",
      "sourceSheet": "湖南交易中心-湖南数据-取数工具",
      "dataCategory": "实际",
      "dataName": "发电总出力",
      "dataSubItem": "发电总出力",
      "priority": "P1",
      "timePoint": "15min",
      "pageAddress": "信息披露-信息披露查询-现货及辅助服务-省内现货-运行信息-发电总出力",
      "downloadFile": "8.2._【事后】发电总出力.xlsx",
      "disclosureTime": "D日12时后出D-1日",
      "valueRange": "D-7->D-1",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "hunan",
      "tradeCenter": "湖南交易中心",
      "sourceSheet": "湖南交易中心-湖南数据-取数工具",
      "dataCategory": "预测",
      "dataName": "非市场机组总出力预测",
      "dataSubItem": "非市场机组计划总曲线",
      "priority": "P0",
      "timePoint": "15min",
      "pageAddress": "信息披露-信息披露查询-现货及辅助服务-省内现货-预测信息-非市场机组总出力预测",
      "downloadFile": "5.6._【事前】非市场机组总出力预测.xlsx",
      "disclosureTime": "D日出D+1日",
      "valueRange": "D-3至D+1",
      "fetchToolTimeliness": "6点、8点、12点、14点、23点各取一次",
      "remark": "--"
    },
    {
      "tradeCenterKey": "hunan",
      "tradeCenter": "湖南交易中心",
      "sourceSheet": "湖南交易中心-湖南数据-取数工具",
      "dataCategory": "实际",
      "dataName": "非市场机组总出力",
      "dataSubItem": "--",
      "priority": "P0",
      "timePoint": "15min",
      "pageAddress": "信息披露-信息披露查询-现货及辅助服务-省内现货-预测信息-非市场机组总出力",
      "downloadFile": "8.3._【事后】非市场机组总出力.xlsx",
      "disclosureTime": "D日12时后出D-1日",
      "valueRange": "D-4至D-1",
      "fetchToolTimeliness": "6点、8点、12点、14点、23点各取一次",
      "remark": "--"
    },
    {
      "tradeCenterKey": "hunan",
      "tradeCenter": "湖南交易中心",
      "sourceSheet": "湖南交易中心-湖南数据-取数工具",
      "dataCategory": "日前",
      "dataName": "日前节点边际电价",
      "dataSubItem": "节点电能量价格",
      "priority": "P1",
      "timePoint": "15min",
      "pageAddress": "信息披露-信息披露查询-现货及辅助服务-省内现货-现货市场申报出清信息-日前节点边际电价",
      "downloadFile": "6.3._【事后】日前节点边际电价.xlsx",
      "disclosureTime": "D日出D-1日",
      "valueRange": "D-3至D+1",
      "fetchToolTimeliness": "6点、8点、12点、14点、23点各取一次",
      "remark": "--"
    },
    {
      "tradeCenterKey": "hunan",
      "tradeCenter": "湖南交易中心",
      "sourceSheet": "湖南交易中心-湖南数据-取数工具",
      "dataCategory": "实时",
      "dataName": "实时节点边际电价",
      "dataSubItem": "节点电能量价格",
      "priority": "P0",
      "timePoint": "15min",
      "pageAddress": "信息披露-信息披露查询-现货及辅助服务-省内现货-现货市场申报出清信息-实时节点边际电价",
      "downloadFile": "6.4._【事后】实时节点边际电价 (1).xlsx",
      "disclosureTime": "D日12时后出D-1日",
      "valueRange": "D-3至D+1",
      "fetchToolTimeliness": "6点、8点、12点、14点、23点各取一次",
      "remark": "--"
    },
    {
      "tradeCenterKey": "hunan",
      "tradeCenter": "湖南交易中心",
      "sourceSheet": "湖南交易中心-湖南数据-取数工具",
      "dataCategory": "日前",
      "dataName": "日前用户侧统一结算价格",
      "dataSubItem": "--",
      "priority": "P0",
      "timePoint": "1H",
      "pageAddress": "信息披露-信息披露查询-现货及辅助服务-省内现货-现货市场申报出清信息-日前用户侧统一结算价格",
      "downloadFile": "6.10._【事后】日前用户侧统一结算价格 (2).xlsx",
      "disclosureTime": "D日12时后出D日",
      "valueRange": "D-3至D",
      "fetchToolTimeliness": "6点、8点、12点、14点、23点各取一次",
      "remark": "--"
    },
    {
      "tradeCenterKey": "hunan",
      "tradeCenter": "湖南交易中心",
      "sourceSheet": "湖南交易中心-湖南数据-取数工具",
      "dataCategory": "实时",
      "dataName": "实时用户侧统一结算价格",
      "dataSubItem": "--",
      "priority": "P0",
      "timePoint": "1H",
      "pageAddress": "信息披露-信息披露查询-现货及辅助服务-省内现货-现货市场申报出清信息-实时用户侧统一结算价格",
      "downloadFile": "6.11._【事后】实时用户侧统一结算价格 (4).xlsx",
      "disclosureTime": "D日出D-4日",
      "valueRange": "D-7至D-4",
      "fetchToolTimeliness": "6点、8点、12点、14点、23点各取一次",
      "remark": "--"
    },
    {
      "tradeCenterKey": "hunan",
      "tradeCenter": "湖南交易中心",
      "sourceSheet": "湖南交易中心-湖南数据-取数工具",
      "dataCategory": "实际",
      "dataName": "日结算单查询",
      "dataSubItem": "售电公司日用电信息",
      "priority": "P0",
      "timePoint": "1H",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "hunan",
      "tradeCenter": "湖南交易中心",
      "sourceSheet": "湖南交易中心-湖南数据-取数工具",
      "dataCategory": "实际",
      "dataName": "日用电信息（现货）",
      "dataSubItem": "--",
      "priority": "P0",
      "timePoint": "1H",
      "pageAddress": "信息披露-用户用电信息查询-日用电信息（现货）",
      "downloadFile": "现货日用电信息-售电公司_REPORT0 (4).xlsx",
      "disclosureTime": "D日出D-2日",
      "valueRange": "D-2至D-2",
      "fetchToolTimeliness": "6点、8点、12点、14点、23点各取一次",
      "remark": "--"
    },
    {
      "tradeCenterKey": "hunan",
      "tradeCenter": "湖南交易中心",
      "sourceSheet": "湖南交易中心-湖南数据-取数工具",
      "dataCategory": "实际",
      "dataName": "日滚搓量价（卖1至卖5，买1至买5）",
      "dataSubItem": "--",
      "priority": "P0",
      "timePoint": "10s",
      "pageAddress": "--",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "hunan",
      "tradeCenter": "湖南交易中心",
      "sourceSheet": "湖南交易中心-湖南数据-取数工具",
      "dataCategory": "实际",
      "dataName": "日前申报",
      "dataSubItem": "--",
      "priority": "--",
      "timePoint": "15min",
      "pageAddress": "现货交易_省内-现货申报（用电侧）",
      "downloadFile": "电能量申报数据 (1).xlsx",
      "disclosureTime": "D日申报后即有数据",
      "valueRange": "D至D+1",
      "fetchToolTimeliness": "14点取一次",
      "remark": "--"
    },
    {
      "tradeCenterKey": "hunan",
      "tradeCenter": "湖南交易中心",
      "sourceSheet": "湖南交易中心-湖南数据-取数工具",
      "dataCategory": "实际",
      "dataName": "中长期交易结果",
      "dataSubItem": "--",
      "priority": "P2",
      "timePoint": "--",
      "pageAddress": "中长期交易-结果查询",
      "downloadFile": "--",
      "disclosureTime": "--",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "交易品种 查询条件不一致"
    },
    {
      "tradeCenterKey": "hunan",
      "tradeCenter": "湖南交易中心",
      "sourceSheet": "湖南交易中心-湖南数据-取数工具",
      "dataCategory": "实际",
      "dataName": "机组状态",
      "dataSubItem": "--",
      "priority": "--",
      "timePoint": "15min",
      "pageAddress": "信息披露-综合查询-电网运行-机组状态",
      "downloadFile": "8.1._【事后】机组状态.xlsx",
      "disclosureTime": "D日17点之后出D-1",
      "valueRange": "D-2至D-1",
      "fetchToolTimeliness": "17点、18点、23点各取一次",
      "remark": "--"
    },
    {
      "tradeCenterKey": "hunan",
      "tradeCenter": "湖南交易中心",
      "sourceSheet": "湖南交易中心-湖南数据-取数工具",
      "dataCategory": "实际",
      "dataName": "日清算",
      "dataSubItem": "--",
      "priority": "--",
      "timePoint": "1H",
      "pageAddress": "结算-结算单查询",
      "downloadFile": "北京小桔新能源汽车科技有限公司01售电公司日清分结算单.pdf",
      "disclosureTime": "D日最早出D-4日",
      "valueRange": "D-10至D-3日",
      "fetchToolTimeliness": "--",
      "remark": "--"
    },
    {
      "tradeCenterKey": "hunan",
      "tradeCenter": "湖南交易中心",
      "sourceSheet": "湖南交易中心-湖南数据-取数工具",
      "dataCategory": "实际",
      "dataName": "月结算-售电公司",
      "dataSubItem": "--",
      "priority": "--",
      "timePoint": "1M",
      "pageAddress": "结算-结算单查询-售电公司",
      "downloadFile": "北京小桔新能源汽车科技有限公司售电公司-核对版结算单.pdf",
      "disclosureTime": "M月10日后出M-1月数据",
      "valueRange": "M-1月",
      "fetchToolTimeliness": "M月10日取到一次即可",
      "remark": "--"
    },
    {
      "tradeCenterKey": "hunan",
      "tradeCenter": "湖南交易中心",
      "sourceSheet": "湖南交易中心-湖南数据-取数工具",
      "dataCategory": "实际",
      "dataName": "月结算-用电企业",
      "dataSubItem": "--",
      "priority": "--",
      "timePoint": "1M",
      "pageAddress": "结算-结算单查询-用电企业",
      "downloadFile": "北京小桔新能源汽车科技有限公司中长期月结算之零售用户明细分时excel结算单.xlsx",
      "disclosureTime": "M月10日后出M-1月数据",
      "valueRange": "M-1月",
      "fetchToolTimeliness": "M月10日取到一次即可",
      "remark": "--"
    },
    {
      "tradeCenterKey": "hunan",
      "tradeCenter": "湖南交易中心",
      "sourceSheet": "湖南交易中心-湖南数据-取数工具",
      "dataCategory": "实际",
      "dataName": "结算总体情况及分类构成情况（日）",
      "dataSubItem": "--",
      "priority": "--",
      "timePoint": "1D",
      "pageAddress": "信息披露-信息披露查询-市场运营-结算情况-结算总体情况及分类构成情况（日）",
      "downloadFile": "2026年04月30日结算总体情况及分类构成情况.pdf",
      "disclosureTime": "不定时",
      "valueRange": "D-10至D-1",
      "fetchToolTimeliness": "14点取一次",
      "remark": "--"
    },
    {
      "tradeCenterKey": "hunan",
      "tradeCenter": "湖南交易中心",
      "sourceSheet": "湖南交易中心-湖南数据-取数工具",
      "dataCategory": "实际",
      "dataName": "系统备用信息",
      "dataSubItem": "负备用",
      "priority": "--",
      "timePoint": "15min",
      "pageAddress": "信息披露-信息披露查询-电网运行-系统备用信息",
      "downloadFile": "8.7._【事后】系统备用信息.xlsx",
      "disclosureTime": "D日17点之后出D-1",
      "valueRange": "D-2至D-1",
      "fetchToolTimeliness": "17点、18点、23点各取一次",
      "remark": "--"
    },
    {
      "tradeCenterKey": "hunan",
      "tradeCenter": "湖南交易中心",
      "sourceSheet": "湖南交易中心-湖南数据-取数工具",
      "dataCategory": "实际",
      "dataName": "系统备用信息",
      "dataSubItem": "正备用",
      "priority": "--",
      "timePoint": "15min",
      "pageAddress": "信息披露-信息披露查询-电网运行-系统备用信息",
      "downloadFile": "--",
      "disclosureTime": "D日17点之后出D-1",
      "valueRange": "D-2至D-1",
      "fetchToolTimeliness": "17点、18点、23点各取一次",
      "remark": "--"
    },
    {
      "tradeCenterKey": "hunan",
      "tradeCenter": "湖南交易中心",
      "sourceSheet": "湖南交易中心-湖南数据-取数工具",
      "dataCategory": "实际",
      "dataName": "发输变电设备检修计划（日）",
      "dataSubItem": "--",
      "priority": "P0",
      "timePoint": "1D",
      "pageAddress": "信息披露-信息披露查询-供需与约束-约束信息-发输变电设备检修计划（日）",
      "downloadFile": "发输变电设备检修计划-日.xlsx",
      "disclosureTime": "D日出D+1",
      "valueRange": "--",
      "fetchToolTimeliness": "--",
      "remark": "--"
    }
  ]
};
})(window);
